### ISSUE TITLE
Bug: Getting 401 error on search

### ISSUE THREAD

**Issue by Anushka7310** [Anushka7310/Music-PLaylist-Webapp#2]
**Problem*
When a user tries to search for a song or artist, nothing displays on the screen and a 401 error can be seen on the console.

This is most probably due to expired client_id

**Comment by mgilberties** [comment]
Hi there, 

Bit of a non starter this one, fixed some broken references (semantic.min.js and a jQuery dependency) but not able to make much progress with the Soundcloud API. I tried to register to get my own client ID to debug but get presented with the following:

<img width="649" alt="Screenshot 2021-10-11 at 8 30 12 pm" src="https://user-images.githubusercontent.com/1201720/136846213-6767bf68-c0d0-4aef-9289-554660e1d1e3.png">

I'm wondering if they have just abandoned the API altogether?  Let me know if you would like me to make a PR with my fixes in thus far, as small as they are.

Cheers,

Max
